{"code":209,"level":"error","message":"Invalid session token","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Auth.js:192:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleParseSession (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\middlewares.js:292:21)","timestamp":"2024-03-19T21:20:09.248Z"}
{"code":209,"level":"error","message":"Invalid session token","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Auth.js:192:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleParseSession (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\middlewares.js:292:21)","timestamp":"2024-03-19T21:20:09.253Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs2894488@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs2894488@gmail.com","password":"********"},"timestamp":"2024-03-19T21:21:12.297Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-03-19T21:21:12.301Z"}
