{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T15:31:23.988Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T15:31:24.000Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T15:31:26.383Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T15:31:26.389Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T15:33:28.662Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T15:33:28.677Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T15:33:31.571Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T15:33:31.576Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T15:34:26.176Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T15:34:26.190Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T16:03:41.311Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T16:03:41.321Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-28T16:03:43.748Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-28T16:03:43.752Z"}
