{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS27106@GMAIL.COM\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS27106@GMAIL.COM","password":"********"},"timestamp":"2024-04-30T03:07:43.926Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:07:43.938Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS27106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:08:05.894Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:08:05.898Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS27106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:08:15.942Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:08:15.950Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS27106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:08:17.068Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:08:17.071Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:08:43.663Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:08:43.667Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:09:21.756Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:21.761Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:09:23.118Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:23.120Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:09:23.897Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:23.900Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:09:40.731Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:40.734Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"FS2106@gmail.com","password":"********"},"timestamp":"2024-04-30T03:09:44.244Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:44.249Z"}
{"error":{"code":1,"message":"An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality."},"functionName":"reset-password","level":"error","message":"Failed running cloud function reset-password for user undefined with:\n  Input: {\"email\":\"FS2106@gmail.com\"}\n  Error: {\"message\":\"An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.\",\"code\":1}","params":{"email":"FS2106@gmail.com"},"timestamp":"2024-04-30T03:09:52.288Z"}
{"code":1,"level":"error","message":"An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.","stack":"Error: An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.\n    at UsersRouter._throwOnBadEmailConfig (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\UsersRouter.js:350:15)\n    at UsersRouter.handleResetRequest (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\UsersRouter.js:357:10)\n    at Object.handler (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\UsersRouter.js:562:19)\n    at C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\PromiseRouter.js:130:13\n    at new Promise (<anonymous>)\n    at PromiseRouter.tryRouteRequest (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\PromiseRouter.js:129:12)\n    at C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\ParseServerRESTController.js:134:25\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T03:09:52.293Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs271062@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs271062@gmail.com","password":"********"},"timestamp":"2024-04-30T16:41:13.644Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T16:41:13.652Z"}
